### ISSUE TITLE
Desenhar os wireframes

### ISSUE THREAD

**Issue by l30n1** [AppFriends/iOrder#11]
Lista de wireframes a serem desenhados.

**Comment by damasio34** [comment]
- Login
- Dashbord (pode deixar pra depois)
- Cardápio
- Item do cardápio (com os itens customisáveis do cardápio, pro usuário poder acrescentar ou remover);
- Pedido
- Pagamento

Acho que o básico é isso. :)

**Comment by l30n1** [comment]
![home](https://cloud.githubusercontent.com/assets/13289837/18597055/8281bf42-7c22-11e6-9cba-731de1ca8d09.png)

**Comment by l30n1** [comment]
![cadastre-se](https://cloud.githubusercontent.com/assets/13289837/18597131/e6920eba-7c22-11e6-8f7c-c388cdb4ec31.png)

**Comment by l30n1** [comment]
![esqueceu_a_senha_](https://cloud.githubusercontent.com/assets/13289837/18597147/f1fe5e98-7c22-11e6-8524-265357f089d8.png)

**Comment by l30n1** [comment]
da pra melhorar mas o check in ta aí

![checkin](https://cloud.githubusercontent.com/assets/13289837/18600910/760ed1dc-7c36-11e6-8c2c-483f75b85734.png)

**Comment by l30n1** [comment]
![nome_do_local](https://cloud.githubusercontent.com/assets/13289837/18600932/8e833e4c-7c36-11e6-9ed9-1213293dfd00.png)

**Comment by damasio34** [comment]
O e-mail pode ser o login.
